export const FETCH_TRAINERS_REQUESTED = 'FETCH_TRAINERS_REQUESTED';
export const FETCH_TRAINERS_SUCCESS = 'FETCH_TRAINERS_SUCCESS';
export const FETCH_TRAINERS_FAILED = 'FETCH_TRAINERS_FAILED';

export const FETCH_CATEGORIES_REQUESTED = 'FETCH_CATEGORIES_REQUESTED';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';

export const NEW_TRAINER_REQUESTED = 'NEW_TRAINER_REQUESTED';
export const NEW_TRAINER_SUCCESS = 'NEW_TRAINER_SUCCESS';
export const NEW_TRAINER_FAILED = 'NEW_TRAINER_FAILED';

export const NEW_USER_REQUESTED = 'NEW_USER_REQUESTED';
export const NEW_USER_SUCCESS = 'NEW_USER_SUCCESS';
export const NEW_USER_FAILED = 'NEW_USER_FAILED';