export const FETCH_TRAINERS_REQUESTED = 'FETCH_TRAINERS_REQUESTED';
export const FETCH_TRAINERS_SUCCESS = 'FETCH_TRAINERS_SUCCESS';
export const FETCH_TRAINERS_FAILED = 'FETCH_TRAINERS_FAILED';

export const FETCH_CATEGORIES_REQUESTED = 'FETCH_CATEGORIES_REQUESTED';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';

export const NEW_TRAINER_REQUESTED = 'NEW_TRAINER_REQUESTED';
export const NEW_TRAINER_SUCCESS = 'NEW_TRAINER_SUCCESS';
export const NEW_TRAINER_FAILED = 'NEW_TRAINER_FAILED';

export const NEW_USER_REQUESTED = 'NEW_USER_REQUESTED';
export const NEW_USER_SUCCESS = 'NEW_USER_SUCCESS';
export const NEW_USER_FAILED = 'NEW_USER_FAILED';

export const FETCH_USERS_REQUESTED = 'FETCH_USERS_REQUESTED';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED';

export const GET_CURRENT_USER='GET_CURRENT_USER';
export const SET_CURRENT_USER='SET_CURRENT_USER';

export const FETCH_SESSIONS_REQUESTED = 'FETCH_SESSIONS_REQUESTED';
export const FETCH_SESSIONS_SUCCESS = 'FETCH_SESSIONS_SUCCESS';
export const FETCH_SESSIONS_FAILED = 'FETCH_SESSIONS_FAILED';

export const NEW_SESSION_REQUESTED = 'NEW_SESSION_REQUESTED';
export const NEW_SESSION_SUCCESS = 'NEW_SESSION_SUCCESS';
export const NEW_SESSION_FAILED = 'NEW_SESSION_FAILED';